export const configs = {
  NEXT_PUBLIC_API_GATEWAY: process.env.NEXT_PUBLIC_API_GATEWAY,
  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  NEXT_PUBLIC_IDENTITY_GATEWAY: process.env.NEXT_PUBLIC_IDENTITY_GATEWAY,
  NEXT_PUBLIC_PROTOCOL: process.env.NEXT_PUBLIC_PROTOCOL
    ? process.env.NEXT_PUBLIC_PROTOCOL
    : "https://",
  NEXT_PUBLIC_CLIENT_ID: process.env.NEXT_PUBLIC_CLIENT_ID,
  NEXT_PUBLIC_CLIENT_SECRET: process.env.NEXT_PUBLIC_CLIENT_SECRET,
  NEXT_PUBLIC_SITE_KEY: process.env.NEXT_PUBLIC_SITE_KEY,
  NEXT_PUBLIC_ORG_URL: process.env.NEXT_PUBLIC_ORG_URL,
  NEXT_PUBLIC_WORKSPACE_SLUG: process.env.NEXT_PUBLIC_WORKSPACE_SLUG,
};
