const env = {
  NEXT_PUBLIC_ORG_URL: process.env.NEXT_PUBLIC_ORG_URL,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  NEXT_PUBLIC_API_GATEWAY_VN: process.env.NEXT_PUBLIC_API_GATEWAY_VN,
  NEXT_PUBLIC_API_GATEWAY_NET: process.env.NEXT_PUBLIC_API_GATEWAY_NET,
  NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
  NEXT_PUBLIC_SHIP4P_URL: process.env.NEXT_PUBLIC_SHIP4P_URL,
  NEXT_PUBLIC_JANBOX_CMS_URL: process.env.NEXT_PUBLIC_JANBOX_CMS_URL,
  NEXT_PUBLIC_ICHIBA_PORTAL_CMS_URL:
    process.env.NEXT_PUBLIC_ICHIBA_PORTAL_CMS_URL,
};
export default env;
