version: "3"

services:
  ichiba.homepage:
    container_name: ichiba.homepage
    image: janboxhub/ichiba.homepage:1
    ports:
      - "8035:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    restart: always
networks:
  default:
    external: true
    name: cms-network
